version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: uid:gid
    # network_mode: "host"
    volumes:
      - ~/projects/jellyfin-data/config:/config
      - ~/projects/jellyfin-data/cache:/cache
      - ~/projects/jellyfin-data/media:/media
      - ~/projects/jellyfin-data/media2:/media2:ro
    restart: "unless-stopped"
    ports:
      - 8096:8096
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
